In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

b = np.array([2,3,4,5,6])
print(b)

print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

print(np.__version__)

2.0.2


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

b = np.array([2,3,4,5,6])
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5)) #from tuple to numpy.ndarray

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#0-D Array
import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))

b = np.array(30)
print(b)
print(type(b))

42
<class 'numpy.ndarray'>
30
<class 'numpy.ndarray'>


In [10]:
#1-D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

b = np.array([2,3,4,5,6])
print(b)
print(type(b))

[1 2 3 4 5]
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
#2D array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

b = np.array([[2,3,4],[5,6,7]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>


In [12]:
#3D array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

b = np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7]]])
print(b)
print(type(b))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]]
<class 'numpy.ndarray'>


In [13]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

b = np.array([2,3,4,5,6])
print(b[0])

1
2


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [22]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', b[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [23]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [25]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
